### ISSUE TITLE
Any plain to support `not` pseudo-class selector?

### ISSUE THREAD

**Issue by Mirochiu** [avan06/htmlq#1]
Hi,

I want to use htmlq to filter out the products for coolpc quotation fetched in Mirochiu/execute-daily.

An error is raised with the following command:
`./htmlq -u https://raw.githubusercontent.com/Mirochiu/execute-daily/main/coolpc-20230713.html -a -q 'option[value]:not([disabled])'`

The error message states: "css: unsupported pseudo-class selector: not( at position 13"

Is there any plan to support the `not` pseudo-class selector?

**Comment by avan06** [comment]
Hi,

Thank you for reporting the error information. A new version has been released to fix this issue.
https://github.com/avan06/htmlq/releases/tag/v1.0.5

Currently, there are two popular CSS selector packages available on Golang. One is ericchiang/css, which was still being updated in 2022, and the other is andybalholm/cascadia, which hasn't been updated for a long time. That's why I initially chose to use ericchiang/css. However, it's evident that this package doesn't provide good support for pseudo-class selectors.

**Comment by avan06** [comment]
Hi,

Thank you for reporting the error information.
A new version has been released to fix this issue.
https://github.com/avan06/htmlq/releases/tag/v1.0.5

**Comment by Mirochiu** [comment]
Thanks your for help, v1.0.5 work perfectly
